# Generated by Django 2.1.5 on 2019-08-17 05:23

import autithi.utils.location
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=autithi.utils.location.upload_location, width_field='width_field')),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email must be alphanumaric or contain any of following". @"', regex='^[a-z0-9.@]*$')], verbose_name='email address')),
                ('is_email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_phone_number_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location)),
                ('description', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('id_image1', models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location)),
                ('id_image2', models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location)),
                ('id_type', models.IntegerField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
