# Generated by Django 2.1.5 on 2019-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190817_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
    ]
