# Generated by Django 2.1.5 on 2019-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20190706_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
