# Generated by Django 2.1.5 on 2019-07-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
