# Generated by Django 2.1.5 on 2019-06-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_user', models.BooleanField(default=True)),
                ('request_accepted_by_host', models.BooleanField(default=False)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_conflict', models.BooleanField(blank=True, null=True)),
                ('booking_cancled', models.BooleanField(blank=True, null=True)),
                ('requested_at', models.DateField(auto_now_add=True)),
                ('request_accepted_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_host', to=settings.AUTH_USER_MODEL)),
                ('proparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='property.Proparty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
