# Generated by Django 2.1.5 on 2019-05-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='request_accepted_by_host',
            field=models.BooleanField(default=False),
        ),
    ]
