# Generated by Django 2.1.5 on 2019-05-17 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190517_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='begin_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='date_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
