# Generated by Django 2.1.5 on 2019-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190517_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_cancled',
            field=models.BooleanField(default=False),
        ),
    ]
