# Generated by Django 2.1.5 on 2019-06-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190621_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_cancled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_conflict',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
