# Generated by Django 2.1.5 on 2019-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proparty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proparty',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
