# Generated by Django 2.1.5 on 2019-08-17 12:25

import autithi.utils.location
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proparty', '0002_auto_20190817_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propartyimage',
            name='image',
            field=models.ImageField(upload_to=autithi.utils.location.upload_location),
        ),
    ]
