# Generated by Django 2.1.5 on 2019-08-17 15:18

import autithi.utils.location
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proparty', '0003_auto_20190817_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='proparty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location),
        ),
    ]
