# Generated by Django 2.1.5 on 2019-08-02 06:48

import autithi.utils.location
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190726_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_image1',
            field=models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_imege2',
            field=models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=autithi.utils.location.upload_location),
        ),
    ]
