# Generated by Django 2.1.5 on 2019-08-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190802_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_imege2',
            new_name='id_image2',
        ),
    ]
