# Generated by Django 2.1.5 on 2019-05-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190517_1544'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='begin_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
