# Generated by Django 2.1.5 on 2019-05-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20190517_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='proparty',
        ),
    ]
