# Generated by Django 2.1.5 on 2019-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20190517_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='confirmed',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
