# Generated by Django 2.2 on 2019-06-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20190517_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.Booking'),
        ),
    ]
