# Generated by Django 2.1.5 on 2019-02-06 10:51

from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('place_type', models.CharField(max_length=255)),
                ('rental_type', models.CharField(max_length=255)),
                ('house_rules', models.TextField()),
                ('cancellation_policy', models.TextField()),
                ('amenities', models.CharField(max_length=255)),
                ('number_of_badrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('accommodates', models.CharField(max_length=255)),
                ('times_viewed', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='PropartyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=property.models.upload_location, width_field='width_field')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('proparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Proparty')),
            ],
        ),
    ]
