# Generated by Django 2.1.5 on 2019-06-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_proparty_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proparty',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
